### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by 0xideas** [PrakharSaxena24/RepoForLLMs#1]
Hi Prakhar, thanks for the repo and the medium articles! I found them very helpful. Would you consider adding an open source license to this repo, like MIT or Apache 2.0?

**Comment by PrakharSaxena24** [comment]
I am glad that you found them helpful. 😄 
Thank you for bringing up the issue. I will add an open source license and references in the next push.

**Comment by PrakharSaxena24** [comment]
Added MIT LICENSE in 16db8eb
