### ISSUE TITLE
Problems with model imports

### ISSUE THREAD

**Issue by DrKroll** [PrakharSaxena24/RepoForLLMs#3]
Hi there! 
Thanks for your nice repos. I am trying to fine tune mistral in a google collab notebook. I have a very small datasets and it is actually just for an educational purpose on how to do it. Interesting enough I am getting this error:

ImportError                               Traceback (most recent call last)
[<ipython-input-23-3b34a6793372>](https://524ncxlwzrp-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240410-060226_RC01_623688093#) in <cell line: 2>()
      1 tokenizer = AutoTokenizer.from_pretrained("mistralai/Mixtral-8x7B-Instruct-v0.1")
----> 2 model = AutoModelForCausalLM.from_pretrained("mistralai/Mixtral-8x7B-Instruct-v0.1",
      3                                              load_in_4bit=True,
      4                                              torch_dtype=torch.float16,
      5                                              device_map="auto",

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://524ncxlwzrp-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240410-060226_RC01_623688093#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2943             try:
   2944                 device_map = {"": torch.device(device_map)}
-> 2945             except RuntimeError:
   2946                 raise ValueError(
   2947                     "When passing device_map as a string, the value needs to be a device name (e.g. cpu, cuda:0) or "

ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

Accelerate is installed, I checked it.

**Comment by PrakharSaxena24** [comment]
Hey!
Interesting, 
I see that you are trying to finetune Mixtral.
Did you select the "Runtime type" to GPU, before installing the libraries?
As here, accelerate is supported with GPU.
can you please share the link for google colab notebook?

**Comment by DrKroll** [comment]
This is my notebook. I copied everything, but it is not really working.

https://colab.research.google.com/drive/1Z3zi4H3aIm5K99l1VOVFO3AB0n5KOl2G?usp=sharing￼
Untitled4.ipynb
research.google.com

**Comment by PrakharSaxena24** [comment]
@DrKroll ,
Thanks for sharing. 
It seems to work. 
Since the model is big you need A100 to run it. 
Did you chnage the runtime type. 
Click on "Runtime" on the top bar, then click on "Change Runtime Type" ,  then under  hardware accelerator, select A100.
You need to pay for using it. 
Let me know, if you could solve it.

**Comment by PrakharSaxena24** [comment]
Closing as no further comment.
