### ISSUE TITLE
inference code

### ISSUE THREAD

**Issue by rose-jinyang** [PrakharSaxena24/RepoForLLMs#4]
Hello
How are you?
Thanks for contributing to this project.
Could you add the inference codes of the finetuned checkpoints in your project?

**Comment by PrakharSaxena24** [comment]
Thank you for the comment, I will add a sample inference code too! (Although I have deleted the trained checkpoint, so will use a placeholder instead.)

**Comment by rose-jinyang** [comment]
Hi @PrakharSaxena24 
When will you add the inference code?

**Comment by PrakharSaxena24** [comment]
Hey! 
Apologies for the delay
Added a ipynb for a general template of inference, let mw know if there are any questions. (I cannot use the trained lora as I have deleted the old trained loras)

**Comment by PrakharSaxena24** [comment]
BTW, I would recommend to use [vLLM](https://github.com/vllm-project/vllm) or [TGI](https://huggingface.co/docs/text-generation-inference/en/index),  for optimised inference.
